# Generated by Django 4.1.1 on 2022-09-11 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseTable',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=32)),
                ('amount', models.FloatField()),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
